# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.runs/Clock_synth_1/Clock.dcp
set_property used_in_implementation false [get_files /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.runs/Clock_synth_1/Clock.dcp]
read_verilog {
  /home/aaron/Dropbox/EE324/AudioRecorder/RAMSimulation/cellram_parameters.vh
  /home/aaron/Dropbox/EE324/AudioRecorder/RAMSimulation/subtest.vh
}
read_verilog -library xil_defaultlib {
  /home/aaron/Dropbox/EE324/AudioRecorder/DeBouncer.v
  /home/aaron/Dropbox/EE324/AudioRecorder/TriColorControl.v
  /home/aaron/Dropbox/EE324/AudioRecorder/RAMSimulation/cellram.v
  /home/aaron/Dropbox/EE324/AudioRecorder/RAMSimulation/tb.v
  /home/aaron/Dropbox/EE324/AudioRecorder/WorkingMemoryController.v
  /home/aaron/Dropbox/EE324/SPI_Microphone/SPI-Controller.v
  /home/aaron/Dropbox/EE324/SPI_Microphone/PModMic.v
  /home/aaron/Dropbox/EE324/AudioRecorder/PWMWrapper.v
  /home/aaron/Dropbox/EE324/AudioRecorder/MemoryController.v
  /home/aaron/Dropbox/EE324/AudioRecorder/ClockDivider.v
  /home/aaron/Dropbox/EE324/AudioRecorder/AudioController.v
  /home/aaron/Dropbox/EE324/AudioRecorder/MicrophoneWrapper.v
}
read_xdc /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.srcs/constrs_1/imports/FPGAStuff/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.srcs/constrs_1/imports/FPGAStuff/Nexys4_Master.xdc]

catch { write_hwdef -file AudioRecorder.hwdef }
synth_design -top AudioRecorder -part xc7a100tcsg324-1
write_checkpoint -noxdef AudioRecorder.dcp
catch { report_utilization -file AudioRecorder_utilization_synth.rpt -pb AudioRecorder_utilization_synth.pb }
