# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.srcs/sources_1/ip/Clock/Clock.xci
# IP: The module: 'Clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.srcs/sources_1/ip/Clock/Clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.srcs/sources_1/ip/Clock/Clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.srcs/sources_1/ip/Clock/Clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.srcs/sources_1/ip/Clock/Clock.xci
# IP: The module: 'Clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.srcs/sources_1/ip/Clock/Clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.srcs/sources_1/ip/Clock/Clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/aaron/Dropbox/EE324/AudioRecorder/project_1/project_1.srcs/sources_1/ip/Clock/Clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
